### ISSUE TITLE
[1.14.4] Iron Chests support incorrectly reports failure, causes console spam

### ISSUE THREAD

**Issue by firegodjr** [blay09/RefinedRelocation2#108]
Running RR2 6.3.0 on 1.14.4, it appears to access a class from Iron Chests ("GenericIronChestTileEntity") before Iron Chests registers its items. As a result, right clicking on nearly anything in-game writes to the server console that "IronChest compat did not setup correctly". Obviously, this drowns out any other meaningful console output, and causes unnecessary load.

Notably, I can still _craft_ iron sorting chests, and they still obey their set filters, leading me to believe that things still registered correctly in the end. The issue is entirely console-based.

Log from my server containing the issue:
https://pastebin.com/K0w7uQrq

**Comment by kkjdroid** [comment]
I'm also having this issue, but my log is 900KiB and won't fit on Pastebin. I don't even use the mod, so you don't have to craft anything to get the errors.
