### ISSUE TITLE
Sorting seems to break down after an hour or so.

### ISSUE THREAD

**Issue by Divineaspect** [blay09/RefinedRelocation2#110]
So I'm using this in my factory (1.14) on a server and it seems to stop working after about an hour. When that happens even separate sorting chest arrays stop sorting.

**Comment by BlayTheNinth** [comment]
Is there anything suspicious in the logs?

**Comment by Divineaspect** [comment]
It's on a server so that'll take some time to check.

**Comment by Divineaspect** [comment]
woot, ok server access attained, anything I should be looking for?

**Comment by BlayTheNinth** [comment]
Pretty much anything that contains "refinedrelocation" or "Exception" could be useful. Are you using Sorting Connectors or how were your chests connected?

**Comment by Divineaspect** [comment]
ok, so it seems to result from the intersection of matching chest priorities, across chunks.

**Comment by BlayTheNinth** [comment]
Still unable to reproduce this, if anyone knows a setup to consistently reproduce the issue with it'll be a big help.

**Comment by Divineaspect** [comment]
It was using sorting iron chests, and we nailed it down to destination chests  filling in a different chunk, it would not go looking for new destinations for things, and it would clog up.

**Comment by BlayTheNinth** [comment]
Closing this for now since there hasn't been any recent reports of issues like this.
