### ISSUE TITLE
Everything dissappeared after restarting my server. 

### ISSUE THREAD

**Issue by cbrules3033** [blay09/RefinedRelocation2#115]
Hello, I have been running this mod for months now on my server without incident. Randomly, just now, all of my sorting chests and wires vanished. Along with all of the items within them.

**Comment by cbrules3033** [comment]
Minecraft version 1.16.1

**Comment by BlayTheNinth** [comment]
Need the logs. Have any mods been added, removed or updated before it happened? Is the mod still being loaded at all?
