### ISSUE TITLE
8.2.1 - Gold and diamond chests differ in slots to the Iron Chests mod

### ISSUE THREAD

**Issue by Lystraeus** [blay09/RefinedRelocation2#118]
Thankyou for your mod :)

As for the issue, IC 1.16 gold chests are 9x9 (rather than 12x7); and diamond chests are 12x9 (rather than 16x7).

**Comment by BlayTheNinth** [comment]
This was intentional, I couldn't stand the way it looked when columns were added and decided to sacrifice those 3-4 slots for the greater good. I believe when upgrading it should drop all extra items that couldn't fit.

**Comment by Lystraeus** [comment]
Fair enough. I'll close this as works as intended.
