### ISSUE TITLE
Input Filter not consumed

### ISSUE THREAD

**Issue by aparhatus** [blay09/RefinedRelocation2#17]
Minecraft: 1.11.2
Forge: 13.20.0.2270
Refined Relocation 2: 3.1.5
Iron Chests: 7.0.18.800

Inserting an Input Filter into a Sorting Iron Chest does not consume the Input Filter, it is dropped on the ground. The filter gets applied in the chest anyway, which allows for an infinite amount of uses of the same Input Filter.

Haven't tested it with other filters or chests.

**Comment by BlayTheNinth** [comment]
The Input Filter is a module for the Block Extender, it has no use anywhere else.

Sorting (Iron) Chests come with filter functionality by default.

**Comment by aparhatus** [comment]
Well, now I feel really stupid. Sorry for wasting your time and thank you for explaining!

Edit: Does the regular Sorting Chest (plain wooden one) have any filter functionality? I don't see any GUI for it.

**Comment by BlayTheNinth** [comment]
It should, try shift-right clicking it or clicking the filter button in the top right of the GUI.

**Comment by aparhatus** [comment]
Sneaking with shift highlights it with a yellow outline. But right clicking it while it's highlighted does nothing. 

http://i.imgur.com/je8AjCH.png

The GUI does not have the button the Sorting Iron Chest does either.

http://i.imgur.com/DGZSrjF.png

The sorting itself does work if I position it next to the iron chest - the items leave the wooden chest and enter the iron chest according to its filter. However I don't see a way for the wooden chest to have a filter of its own.

Edit: Sorry, saw you literally just fixed it. Thank you very much!
