### ISSUE TITLE
Suggestions and Issues

### ISSUE THREAD

**Issue by Konclan** [blay09/RefinedRelocation2#19]
- There is no easy way to do corners, Only way I've found to do it is to place a wooden sorting chest that blacklists everything between the two chest groups. Maybe add support for this or add an item that helps connect chest groups.
![2017-05-24_06 25 47](https://cloud.githubusercontent.com/assets/16567080/26401117/e5512d42-4049-11e7-9b34-807276f032e0.png)

- You cannot open an iron sorting chest below another iron sorting chest without editing the filter and clicking the chest button; However, you can open a wooden sorting chest under an iron sorting chest. You can also open any sorting chest by editing the filter and clicking the chest icon even if its under a block.

- For some reason mods like Hammerz arnt listed in the Mod Filter.
![2017-05-24_06 43 52](https://cloud.githubusercontent.com/assets/16567080/26402174/cd654fba-404e-11e7-9999-998ecad9edee.png)

- Name Filter's scroll wheel is extremely bugged and doesn't recognize the last couple lines.
![scrollbug](https://cloud.githubusercontent.com/assets/16567080/26401890/89fee5c0-404d-11e7-910f-96a24812dbb4.gif)

- Some strange things happening with servers. The name filter won't recognize items from Hammerz or Reliquary
![2017-05-24_06 57 26](https://cloud.githubusercontent.com/assets/16567080/26402029/471a10c6-404e-11e7-98e6-7e909faa03fd.png)

I hope most or all of these are fixed. Thank you for all that you do and keep up the great work 👍

**Comment by Konclan** [comment]
Oh one more thing, for some reason I can walk into chests with no block under them and take a second of suffocation damage, its nothing major just a bit annoying

**Comment by Konclan** [comment]
Miss click *facepalm*

**Comment by BlayTheNinth** [comment]
What mod version are you on?

**Comment by Konclan** [comment]
![capture](https://cloud.githubusercontent.com/assets/16567080/26531967/b9d15dd0-43ba-11e7-8563-71624ad25b91.PNG)
Huh...

Anyways its RefinedRelocation-mc1.11.2-3.1.8.jar

**Comment by Konclan** [comment]
Are you planning on adding ore dictionary sorting at some point?

**Comment by BlayTheNinth** [comment]
Fixed most of these in the next version and extracted the two feature requests into their own issues (#24 #25) for better tracking.

Regarding the name filtering on servers, I believe this is due to the server not loading the language files (could be the case when running a server on linux with an incorrectly cased language file name). In a recent Minecraft version, language files became all lower-case and not everyone has adapted yet (since it appears to work correctly in some cases).
