### ISSUE TITLE
Crash with latest iron chest (class not found)

### ISSUE THREAD

**Issue by Ozzymud** [blay09/RefinedRelocation2#26]
Updated iron chest to be confronted by a crahsh: 

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Refined Relocation (refinedrelocation)
Caused by: java.lang.NoClassDefFoundError: cpw/mods/ironchest/TileEntityIronChest  

ironchest{1.11.2-7.0.21.806} [Iron Chest] (ironchest-1.11.2-7.0.21.806.jar) 
refinedrelocation{3.1.13} [Refined Relocation] (RefinedRelocation-mc1.11.2-3.1.13.jar)   

Full log: https://pastebin.com/dzcvxKUm

**Comment by kreezxil** [comment]
Confirmed:

Issue:  3.1.13 crashes dedicated server Forge 1.11.2 build 2315

Notes:
     iron chests updated to 1.11.2-7.0.21.806 thus breaking your mod somehow. :(

crash report:
https://gist.github.com/678a607fa33f7f525b1e7d4946bebb1b

fml server latest:
https://gist.github.com/986fd74d1b16309d3426c91199e1cab1
