### ISSUE TITLE
Iron Chests should be a required dependency

### ISSUE THREAD

**Issue by trabpukcip** [blay09/RefinedRelocation2#30]
It may seem obvious but Iron Chests should be a required dependency for this mod to work. Users would then get a much nicer stop error screen in game, rather than reading a crash log.

`java.lang.NoClassDefFoundError: cpw/mods/ironchest/common/tileentity/chest/TileEntityIronChest`

More ideally the mod could be recoded the mod to only allow vanilla wood chests if Iron Chests is not found or if the user does not want to use them for some reason.

**Comment by BlayTheNinth** [comment]
It's already written in such a way that Iron Chests is a soft dependency, it just had an oversight. You should always post the full crash log, as just that one line doesn't contain all the necessary information to quickly track the error down.
