### ISSUE TITLE
No filters selectable

### ISSUE THREAD

**Issue by rlnt** [blay09/RefinedRelocation2#31]
Currently, you can't select any filters in the newest version. Nothing happens if you click on them and also it was written that block extenders and hoppers are already included but there is nothing like this. Please fix the filter selection at least.

**Comment by rlnt** [comment]
Edit: seems like it happens only sometimes

If you run into that issue you have to restart the server and then you can select filters.

**Comment by BlayTheNinth** [comment]
What is "newest version"?

**Comment by rlnt** [comment]
I am playing on 1.10.2 and the latest version is from June 6th, 2k17 and it's the 2.1.24.
And it seems like you can select 2 filters after some restarts and then this bug appears again.

**Comment by BlayTheNinth** [comment]
Ugh, looks like my fix back then un-broke half the filters, but broke the other half that worked before. Fixed version should be up on Curse now.

**Comment by rlnt** [comment]
Thank you very much. I'll test that :)
