### ISSUE TITLE
[Issue] Crash with placing Bonsai-trees

### ISSUE THREAD

**Issue by accessdenied0** [blay09/RefinedRelocation2#37]
Greetings @blay09 ,

I have the strange issue, that everytime I try to place down a Hoppered-Bonsai-pot from [Bonsai-trees](https://minecraft.curseforge.com/projects/bonsai-trees), my instance crashes.

[Not sure it is the fault of this mod, but this was my best indicator.](https://pastebin.com/dLgy7tGd)

Thank you for any help.

access_denied

**Comment by BlayTheNinth** [comment]
Actually an isssue on Bonsai Trees side as they're returning the wrong capability without checking what was requested, but since this is the second time this has happened with another mod I added an additional check to prevent the crash. In a perfect world this wouldn't be necessary. v_v
