### ISSUE TITLE
Quark support

### ISSUE THREAD

**Issue by BBoldt** [blay09/RefinedRelocation2#4]
Quark adds new wood chest variants for all the vanilla woods.

http://quark.vazkii.us/#module-world

![](http://quark.vazkii.us/img/decoration/chests.jpg)

**Comment by BlayTheNinth** [comment]
Next version will use an OreDictionary chest in the Sorting Chest recipe so they can at least be used in crafting. Having them take on the texture is low-priority until I get the other features in.

**Comment by BlayTheNinth** [comment]
#6
