### ISSUE TITLE
Normal Sorting chests are placed backwards

### ISSUE THREAD

**Issue by Dalethium** [blay09/RefinedRelocation2#41]
Minecraft Version: 1.11.2
FML: MCP 9.38 Powered by Forge 13.20.1.2386 97 mods loaded, 97 mods active
UCHIJAAAA	refinedrelocation{3.1.15} [Refined Relocation] (RefinedRelocation-mc1.11.2-3.1.15.jar) 

As the title says, also, it may be worth noting that sorting chests that are based on the iron chests mod face the correct direction when placed.

(Chests should face you when placed, these face away)

**Comment by BlayTheNinth** [comment]
This is already fixed on 1.12.2 and older versions only get critical bug fixes at this point.

Edit: Nevermind, releasing a new build anyway...
