### ISSUE TITLE
Sorting Hoppers don't retain their priority

### ISSUE THREAD

**Issue by luke-bravenboer** [blay09/RefinedRelocation2#45]
Unlike sorting chests, sorting hoppers don't seem to retain their priority; changing the priority to anything other than normal, closing the GUI, then re-opening the GUI, shows that it's still set to 'Normal'.

Refined Relocation 2: 1.12.2-4.2.23
Forge: 14.23.3.2675

**Comment by BlayTheNinth** [comment]
It shouldn't have shown up to begin with, filtered hoppers do not count as target inventories for a sorting network (therefore they can't have a priority).
