### ISSUE TITLE
[Suggestion]: Metal Chests Support?

### ISSUE THREAD

**Issue by Akitori** [blay09/RefinedRelocation2#48]
Hiya. I kinda wanted to use Metal Chests as its far cluttered/full compared to Iron chests. (mod is here https://minecraft.curseforge.com/projects/metalchests)

Any chance of adding support?

**Comment by BlayTheNinth** [comment]
Adding native support for other mods on my side has a high maintenance overhead and may unexpectedly break, so I'd like to keep it to a minimum (and only support the most essential mods by default). You can use the Sorting Interface to connect Metal Chests chests though.
