### ISSUE TITLE
[1.14] NullPointerException

### ISSUE THREAD

**Issue by MasterEnderman** [blay09/RefinedRelocation2#69]
Forge: 28.1.74
Crash-Report: https://pastebin.com/ZdmZ4J2P
Minecraft: 1.14.4
RefinedRelocation2: 6.2.4

**Comment by BlayTheNinth** [comment]
Whatever block you were looking at is returning a null value for `getCapability` even though it's not allowed. I'm adding a safe guard since mods keep doing getCapability wrong (even several times prior to 1.14), but that mod should also fix it on their end as well.
