### ISSUE TITLE
Block extenders not transparent

### ISSUE THREAD

**Issue by thegamerx1** [blay09/RefinedRelocation2#70]
1.14.4
![image](https://user-images.githubusercontent.com/34986564/71119196-ee6d9400-21d9-11ea-8cc2-af026efb6292.png)

**Comment by BlayTheNinth** [comment]
Are you using OptiFine or something? They're rendering fine for me on Forge 28.1.109.

![image](https://user-images.githubusercontent.com/1933180/71541088-c3124400-2953-11ea-835c-6c821d958950.png)

**Comment by thegamerx1** [comment]
I am using optifine but because i need it my fps arent that high 35-50 on vanilla and 45-85 with optifine

**Comment by BlayTheNinth** [comment]
If this is only happening with OptiFine installed, there's nothing I can do. OptiFine does base changes that will sometimes conflict with other mods.
