### ISSUE TITLE
Mod Conflict between Refined Relocation 2 and Fairy Lights

### ISSUE THREAD

**Issue by Howlingwolf1011** [blay09/RefinedRelocation2#73]
On the public All The Mods 4 server, which uses both mods, i came across a instant game-breaking mod conflict.When using the "sorting interface" from Refined Relocation, and placing it facing into a "Sorting Chest" from the same mod, caused insta-disconnect, and disconnects anytime i try to log back in, when my GF logged in as well, it kicked her as well due to being in the same chunks i was. The bug report mentions "Fairy Lights" so we made a creative single player world with the mod pack and did the same steps, causing the same crash. We then tried removing Fairy Lights from the mod pack and loading it back up, which instantly fixed the issue.
[crash-2020-01-13_21.27.39-client.txt](https://github.com/blay09/RefinedRelocation2/files/4059796/crash-2020-01-13_21.27.39-client.txt)

PS. ATM4 and Fairy Lights have both been made aware of this as well.

**Comment by BlayTheNinth** [comment]
By the way, I'd recommend against connecting a sorting interface to a sorting chest, as the chest will infinitely sort into itself, which is fun to look at but not too useful. :P

Sorting Chests already provide the sorting functionality by themselves, the Sorting Interface is for connecting inventories that do not offer sorting functionality.
