### ISSUE TITLE
[1.14.4] Crash with name filter

### ISSUE THREAD

**Issue by MelanX** [blay09/RefinedRelocation2#81]
Here you see a clip what happened in stream with name filter:
https://clips.twitch.tv/LivelyColorfulMilkDatBoi

Here you can find the crash log:
https://pastebin.com/MJAbES3r

Modpack: Sigma 5.0.3
Mod version: RefinedRelocation_1.14.4-6.2.6
Forge version: 28.1.99

**Comment by BlayTheNinth** [comment]
Fix for 1.15+ pending release on CurseForge, backport to 1.14 planned: #104
