### ISSUE TITLE
Fast hopper does not work with hoppers in minecarts

### ISSUE THREAD

**Issue by ethannself** [blay09/RefinedRelocation2#82]
Unlike regular hoppers, the fast hopper will not pull from hoppers in minecarts, Not sure if it's intended or not so decided to post here.
![image](https://user-images.githubusercontent.com/42685193/77880385-8bed5080-722a-11ea-900a-5624b16eb6a3.png)

Modpack: All The Mods 4, latest version on Twitch launcher (updated 3/10/2020)
Mod version: RefinedRelocation_1.14.4-6.2.6
Forge version: 28.2.3

**Comment by BlayTheNinth** [comment]
Fix for 1.15+ pending release on CurseForge
