### ISSUE TITLE
Sorting Interfaces always face North [1.14.4-6.2.6]

### ISSUE THREAD

**Issue by FlexXx1212** [blay09/RefinedRelocation2#83]
Sorting Interfaces can't be rotated with any Wrench or placed facing another direction than North.
And its not only visual, they also only work with blocks on the North side.

![image](https://user-images.githubusercontent.com/33630274/78029870-8b0b0a80-7361-11ea-835a-e6c94a2ac51b.png)

Modpack: SIGMA
Mod version: RefinedRelocation_1.14.4-6.2.6
Forge: 28.1.99

**Comment by andr9528** [comment]
Also occurs in Minecraft 1.15.2 with version RefinedRelocation_1.12.2-701. 

The block allows for xray in 1.15.2. but this you probably already knew from Soaryn on Forgecraft...

**Comment by BlayTheNinth** [comment]
Fix pending release on CurseForge, backport to 1.14 planned: https://github.com/blay09/RefinedRelocation2/issues/104
